### ISSUE TITLE
CID validity test can be improved

### ISSUE THREAD

**Issue by opensaucerer** [lighthouse-web3/encryption-sdk#1]
https://github.com/lighthouse-web3/encryption-sdk/blob/a8bc119e45068e794ca933de4aed624d33ff8592/util/index.js#L5

Great work on the package...
However, I don't think this is the best way to test for cid validity...any validity test of a cid should ideally make use of multibase... don't you think 🤔

Probably check out this [package](https://github.com/multiformats/js-cid)

**Comment by xlassix** [comment]
Yes, we currently run a more extensive validation on the backend Service. We would note the request for the next version release
