### ISSUE TITLE
Is it possible to use the access control with custom Smart Contract Methods?

### ISSUE THREAD

**Issue by hwnprsd** [lighthouse-web3/encryption-sdk#8]
Currently, the supported methods are 
`[ allowance, name, totalSupply, balanceOf, symbol]`

What are the implications of allowing custom methods from custom smart-cotracts? The documentation doesn't contain a lot of info regarding this.

My usecase is the following
I want Kavach access control to work only for members inside a DAO, and thus, I have a `isMember(address)` function in the DAO smart contract which can return a `bool` which I hope can get consumed by Kavach.

**Comment by xlassix** [comment]
@hwnprsd, thanks for reaching out. We will update our docs soon with more examples and details for a smoother developer experience. 
In the meantime, I will help you out with this.

A DAO interface consisting of the snippet below
```solidity
  function isMember(address member) external view returns (bool);
```

would be interpreted as 
``` 
           {
              id: 1,
              chain: "xxxxxx",
              method: "isMember",
              standardContractType: "Custom",
              inputArrayType: ["address"],
              outputType:"bool",
              contractAddress: "0xF...............",
              returnValueTest: { comparator: "==", value: "true" },
              parameters: [":userAddress"],
            }
            ```

**Comment by hwnprsd** [comment]
Got it. I see what I had missed there. Thank you

I now get the following error with no descriptive information:

`{ error: { message: 'condition with ID:1 is invalid', data: {} } }`

This is my code for clarification
```js
    const authMessage: AuthMessage = await getAuthMessage(signer.address);
    const signedMessage = await signer.signMessage(authMessage.message);
    const { error, isSuccess } = await accessControl(
      signer.address,
      cid,
      signedMessage,
      [
        {
          id: 1,
          chain: "Hyperspace",
          method: "isMember",
          standardContractType: "Custom",
          inputArrayType: ["address"],
          outputType: "bool",
          contractAddress: "0x436261368BA84006137bd848131Bd231E40c3352",
          returnValueTest: { comparator: "==", value: "true" },
          parameters: [":userAddress"],
        },
      ],
      "[1]"
    );
```

**Comment by xlassix** [comment]
Hyperspace's RPC is quite unstable at the moment. You could use other supported networks pending when this is resolved by the filecoin team

**Comment by hwnprsd** [comment]
Got it. It works on the Mumbai Testnet.
I have this issue where I get the following error in the same step

```{ error: { message: 'cid not found in encryption', data: {} } }```

Is it possible to look at the node's codebase to see why the errors I'm getting are occuring? That would help contributors contribute to this package as well

**Comment by xlassix** [comment]
@hwnprsd  The issue with Hyperspace has been resolved. kindly give it a try

**Comment by hwnprsd** [comment]
Yup, it works. Thanks!
